==== Country Code Converter

In the Platform Application, you have the option to install a feature called `platform-country-local`.
This feature provides an OSGi service to convert country codes to and from various formats by performing a local lookup.

In order to utilize the country code converter, the `Country Mappings File Locations` field in the feature's configuration must be entered with the file path of each properties file containing country code mappings of the desired country code formats. The feature is already configured by default upon installation, with the file location field pointing to a properties file containing FIPS 10-4 to ISO 3166-1 alpha 3 country code mappings from http://www.opengeocode.org/. This file can be found at: ${branding-lowercase}.home/etc/fips_10_4.properties, and should only be modified in the case the country code mappings would ever change.

A mappings file is always required to convert between some country code format X and the ISO 3166-1 alpha 3 format.

The mappings file contains each mapping in the following format, where the country on the left side of the equals sign is the source format e.g. FIPS 10-4 and the country or countries on the right side of the equals sign are required to be ISO 3166-1 alpha 3 (as that's the normalized country code format), and a new line separating each mapping:

* If there is a single country code from the format X that maps to a single ISO 3166-1 alpha 3 country: AB=ABC
* If there is a single country code from the format X that maps to multiple ISO 3166-1 alpha 3 countries: ZZ=ZZZ,YYY

===== Installing Country Code Converter

The Country Code Converter is not installed by default with a standard installation.
To install:

. Navigate to the *${admin-console}*.
. Select the *${ddf-platform}* application.
. Select the *Features* tab.
. Install the `platform-country-local` feature.

===== Configuring Country Code Converter

To add additional country code mappings files:

. Navigate to the *${admin-console}*.
. Select the *${ddf-platform}* application.
. Select the *Configuration* tab.
. Select the *Local Country Code Converter* configuration.
. Click the  *+* button.
. Add the file path of the new country code mappings file into the new text field that appears.