==== Country Code Converter

In the Platform Application, you have the option to install a feature called `platform-country-local`.
This feature provides an OSGi service to convert country codes into various formats by performing a local lookup.

In order to utilize the FIPS 10-4 to ISO 3166-1 alpha 3 and vice versa country code conversions, the `FIPS 10-4 to ISO 3166-1 alpha 3 File Location` field in the feature's configuration must be entered with the file path of a properties file containing the FIPS 10-4 to ISO 3166-3 alpha 3 country code mappings. The feature is already configured by default upon installation, with the file location field pointing to a properties file containing country code mappings from http://www.opengeocode.org/. This file can be found at: ${branding-lowercase}.home/etc/fipsToIso.properties, and should only be modified in the case the country code mappings would ever change.

The mapping file contains each mapping in the following format, where the country on the left side of the equals sign is FIPS and the country or countries on the right side of the equals sign is ISO, and a new line separating each mapping:

If there is a single FIPS 10-4 country that maps to a single ISO 3166-1 alpha 3 country: AB=ABC

If there is a single FIPS 10-4 country that maps to multiple ISO 3166-1 alpha 3 countries: ZZ=ZZZ,YYY

==== Country Code Converter

In the Platform Application, you have the option to install a feature called `platform-country-local`.
This feature provides an OSGi service to convert country codes into various formats by performing a local lookup.

In order to utilize the FIPS 10-4 to ISO 3166-1 alpha 3 and vice versa country code conversions, the `FIPS 10-4 to ISO 3166-1 alpha 3 File Location` field in the feature's configuration must be entered with the file path of a properties file containing the FIPS 10-4 to ISO 3166-3 alpha 3 country code mappings. The feature is already configured by default upon installation, with the file location field pointing to a properties file containing country code mappings from http://www.opengeocode.org/. This file can be found at: ${branding-lowercase}.home/etc/fipsToIso.properties, and should only be modified in the case the country code mappings would ever change.

The mapping file contains each mapping in the following format, where the country on the left side of the equals sign is FIPS and the country or countries on the right side of the equals sign is ISO, and a new line separating each mapping:

* If there is a single FIPS 10-4 country that maps to a single ISO 3166-1 alpha 3 country: AB=ABC

* If there is a single FIPS 10-4 country that maps to multiple ISO 3166-1 alpha 3 countries: ZZ=ZZZ,YYY

===== Installing Country Code Converter

The Country Code Converter is not installed by default with a standard installation.
To install:

. Navigate to the *${admin-console}*.
. Select the *${ddf-platform}* application.
. Select the *Features* tab.
. Install the `platform-country-local` feature.

===== Configuring Country Code Converter

To modify the path of the FIPS 10-4 to ISO 3166-1 alpha 3 properties file:

. Navigate to the *${admin-console}*.
. Select the *${ddf-platform}* application.
. Select the *Configuration* tab.
. Select the *Local Country Code Converter* configuration.
. Modify the value of the 'FIPS 10-4 to ISO 3166-1 alpha 3 File Location`.